export const constString = {
    appTitle: "Welcome To Visitor Management",
    login: "Login",
    donotHaveAccount: "Don't have account?",
    signup: "Signup",
    userId: "User ID:",
    role: "Role:",
    srno: "SR.no.",
    username: "Username",
    name: "Name",
    nameRequired: "Name is required",
    email: "Email",
    validEmailRequired: "Valid email is required",
    password: "Password",
    passwordRequirement: "Password must be at least 6 characters",
    confirmPassword: "Confirm Password",
    passwordsMustMatch: "Passwords must match",
    address: "Address",
    addressRequired: "Address is required",
    flatno: "Flat No",
    flatRequired: "Flat number is required",
    tower: "Tower",
    towerRequired: "Tower is required",
    action: "Action",
    deleteicon: '/trash.png',
    backicon: "← Back",
    submit: "Submit",
    cancel: "Cancel",
    addGatekeeper: "Add Gatekeeper",
    gatekeeperAddedSyccessfully: "Gatekeeper added successfully!",
    updateProfile: "Update Profile",
    logoutUser: "Logout User",
    saveChanges: "SaveChanges",
    footername:" © 2025 Visitor Management System",
    unauthorizedcode:"404",
    unauthorizedmessage:"Oops! The page you're looking for doesn't exist.",
    unauthorizedButton:"Go back to Home",
    unauthorizedAccess:"Unauthorized Access",
    unauthorizedAccessMessage:"You do not have permission to view this page.",
    goToLogin:"Go to Login",
    approved:"Approved",
    declined:"Declined",
    pending:"Pending",
    addVisitortitle:"Add Visitor",
    addVisitor:"+ Add Visitor",
    addVisitorSuccessfully:"Visitor added successfully",
    dashboard:"Dashboard",
    visitors:"Visitors",
    gatekeepers:"Gatekeepers",
    users:"Users",
    manageUsers:"Manage Users",
    manageGatekeepers:"Manage Gatekeepers",
    manageVisitors:"Manage Visitors",
    approvedVisitors:"Approved Visitors",
    declinedVisitors:"Declined Visitors",
    pendingRequests:"Pending Requests",
    approve:"Approve",
    decline:"Decline",
    visitorsToday:"Visitors Today",
    gatekeeperListTitle:"Gatekeeper List",
    nodeclineVisitorFound:"No Decline Visitors Found",
    approvedVisitorsiconimg:'/approvedVisitors.png',
    pendingVisitorsiconimg:'/clock.png',
    usersiconimg:'/users.png',
    gatekeepericonimg:'/shield.png',
    visitorsTodayiconimg:'/todayVisitors.png',
    declinedVisitoricomimg:'/declinedVisitor.png',
    userListTitle:"User List",
    visitorAvatariconimg:'/visitorAvatar.png',
    manageUsersimg:'/manageUsers.png',
     backgroundicon:'/backgroundIcon.png',
    nopprovedVisitorsFound:"No Approved Visitors Found",
    nopendingVisitorFound:"No Pending Visitors Found",
}